---
deployment:
  tasks:
    - export DEPLOYPATH=/home/clinicbi/public_html/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R icons $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp web.config $DEPLOYPATH
